version: "3.7" # Docker compose version 3.7 es muss mit "" geschrieben werden da 3.7 als String eingelesen werden muss. Wenn es ohne "" gemacht wird, wird es als zahl eingelesen.
services: # services wird gemacht damit man die einzelnen Copntainer aufteilen kann.
 db: # service db
  image: mariadb # image namen von mariadb
  container_name: 
   mariadbt_compose2 # container name
  environment: # enviroment variabeln beim docker run befel wäre das beim -e
    MYSQL_RANDOM_ROOT_PASSWORD: 1 # Bei mir ging die Liste aufzeichnung nicht. (Theorentisch sollte mit einer Liste gehen funktionierte aber bei mir nicht.)
    MYSQL_DATABASE: dbname
    MYSQL_USER: user1
    MYSQL_PASSWORD: user1password
  volumes: # Volume definieren. Man muss Entweder ein Volume erstellt haben oder in diesem File erstellen. WIrd bei Zeile 45 und 46 Erstellt.
   - myvolume:/var/lib/mysql
  networks: # Netzwerk verbindung herstellen mit net 1. Wichtig: man muss das Netzwerk entweder erstellt haben oder in diesem file erstellen. net1 wird auf zeile 43 und 44 erstellt.
   - net1
   # wollte es mit php_myadmin machen. Hat aber zu fehlern geführt. 
 #php_myadmin:
  #image: phpmyadmin/phpmyadmin
  #enviroment:
   #- PMA_HOST=mariadbt
  #depends_on:
   #- db
  #ports:
   #- "8080:80"
  #networks:
   #- net1
 wordpress: # service wordpress
  image: wordpress # image namen von Wordpress
  depends_on:
   - db # Liste von was es braucht um zu Installieren.
  container_name:
   wordpress_compose2 # container name
  environment: # enviroment variabeln beim docker run befel wäre das beim -e
    WORDPRESS_DB_HOST: db:3306 # Bei mir ging die Liste aufzeichnung nicht. (Theorentisch sollte mit einer Liste gehen funktionierte aber bei mir nicht.)
    WORDPRESS_DB_NAME: dbname 
    WORDPRESS_DB_USER: user1
    WORDPRESS_DB_PASSWORD: user1password
  networks: # Netzwerk verbindung herstellen mit net 1. Wichtig: man muss das Netzwerk entweder erstellt haben oder in diesem file erstellen. net1 wird auf zeile 43 und 44 erstellt.
   - net1
  ports: # Port weiterleitung
   - "8081:80"
  volumes: # Volume definieren. Man muss Entweder ein Volume erstellt haben oder in diesem File erstellen. Wird bei Zeile 45 und 47 Erstellt.
   - wp-html:/var/www/html/wp-content
networks: # Deklarieren von Netzwerke. Hier kann man mehrere Netzwerke Definieren.
 net1:
volumes: # volumes Deklarieren. Hier werden die volumes myvolume und wp-html Deklariert.
 myvolume:
 wp-html:
