version: '3.9'

services: 
  db:  
    image: mariadb:latest
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/home/vmadmin/password
      - MYSQL_PASSWORD_FILE=/home/vmadmin/password
      - MYSQL_DATABASE=dbname
      - MYSQL_USER=user1
    networks:
      - net1
    volumes:
      - myvolume:/var/lib/mysql
    secrets:
      - db_root_password
      - db_password

  phpma:
    image: phpmyadmin:latest
    container_name: phpma
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mariadb

  wpress:
    image: wordpress:latest
    container_name: wordpress-test
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=user1
      - WORDPRESS_DB_NAME=dbname
      - WORDPRESS_DB_PASSWORD_FILE=/home/vmadmin/password
    networks:
      - net1
    volumes:
      - wp-html:/var/www/html/wp-content
    secrets:
      - wp_password

volumes:
  myvolume:
  wp-html:

networks:
  net1:
    driver: bridge

secrets:
  db_root_password:
    file: /home/vmadmin/db_root_password
  db_password:
    file: /home/vmadmin/db_password
  wp_password:
    file: /home/vmadmin/wp_password
